name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
change-template: "- $TITLE (#$NUMBER) @$AUTHOR"
change-title-escapes: "\\<*_&"

categories:
  - title: "Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "Bug Fixes"
    labels:
      - "bug"
      - "fix"
  - title: "Documentation"
    labels:
      - "docs"
  - title: "CI/CD"
    labels:
      - "ci"
  - title: "Refactoring"
    labels:
      - "refactor"
  - title: "Chore"
    labels:
      - "chore"
  - title: "Other Changes"
    labels:
      - "*"

template: |
  ## ðŸ“ Changelog
  - [CHANGELOG.md](CHANGELOG.md)

  ## ðŸ”„ What's Changed
  $CHANGES

  ## ðŸŽ‰ New Contributors
  $CONTRIBUTORS

version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "feature"
      - "enhancement"
  patch:
    labels:
      - "bug"
      - "fix"
      - "docs"
      - "chore"
      - "ci"
      - "refactor"
  default: patch

autolabeler:
  - label: "ci"
    files:
      - ".github/workflows/**"
  - label: "docs"
    files:
      - "*.md"
