codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        target: 85%
        informational: true
    patch:
      default:
        informational: true

comment:
  behavior: default
  layout: "header, diff, flags, files"
