//! Type definitions and DTOs for the web channel adapter.

use async_trait::async_trait;
use chrono::{DateTime, Utc};
use dashmap::DashMap;
use proto::{AgentMessage, AgentResponse, ChannelEvent, Role};
use rand::RngCore;
use serde::{Deserialize, Serialize};
use std::sync::{Arc, RwLock};
use tokio::sync::{broadcast, mpsc};

// ─── WsMessage envelope ────────────────────────────────────

/// WebSocket message envelope for client-server communication.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum WsMessage {
    /// Browser requests the latest session list from server memory.
    #[serde(rename = "sessions_request")]
    SessionsRequest,
    /// Server sends TUI-sourced session list to browser.
    #[serde(rename = "sessions_list")]
    SessionsList {
        /// Snapshot of current sessions, aligned with TUI source.
        sessions: Vec<WebSessionEntry>,
    },
    /// Client sends a chat message.
    #[serde(rename = "message")]
    UserMessage {
        /// User-authored text content.
        content: String,
        /// Optional message id generated by the browser for diagnostics.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        message_id: Option<String>,
    },
    /// Server sends an agent response.
    #[serde(rename = "response")]
    AgentReply {
        /// Response text generated by the agent.
        content: String,
        /// Whether the response represents an error.
        is_error: bool,
    },
    /// Server acknowledges that a client message has been queued.
    #[serde(rename = "message_ack")]
    MessageAck {
        /// Optional client-generated message id.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        message_id: Option<String>,
        /// Effective session id used for this message.
        session_id: String,
    },
    /// Server reports an enqueue/send error for a client message.
    #[serde(rename = "message_error")]
    MessageError {
        /// Optional client-generated message id.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        message_id: Option<String>,
        /// Effective session id used for this message.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        session_id: Option<String>,
        /// Human-readable error detail.
        error: String,
    },
    /// Client requests full conversation history for a session.
    #[serde(rename = "session_history_request")]
    SessionHistoryRequest {
        /// Session id whose history is requested.
        session_id: String,
    },
    /// Server sends full conversation history for a session.
    #[serde(rename = "session_history")]
    SessionHistory {
        /// Session id this history belongs to.
        session_id: String,
        /// Ordered list of messages (oldest first).
        messages: Vec<WebHistoryMessage>,
    },
    /// Heartbeat ping from client.
    #[serde(rename = "ping")]
    Ping,
    /// Heartbeat pong from server.
    #[serde(rename = "pong")]
    Pong,
    /// Authentication request from client.
    #[serde(rename = "auth")]
    Auth {
        /// Authentication token supplied by the browser client.
        token: String,
    },
    /// Authentication result from server.
    #[serde(rename = "auth_result")]
    AuthResult {
        /// `true` when authentication succeeds.
        success: bool,
        /// Stable client identifier assigned by the server.
        client_id: Option<String>,
        /// Error message when authentication fails.
        error: Option<String>,
        /// Active provider name selected by the daemon.
        provider: Option<String>,
        /// Active model id selected by the daemon.
        model: Option<String>,
        /// Effective session id bound to this WebSocket connection.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        session_id: Option<String>,
        /// `true` when session is shared with TUI default session.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        shared_with_tui: Option<bool>,
    },
    /// Client requests available model list.
    #[serde(rename = "model_list_request")]
    ModelListRequest,

    /// Server sends available model list.
    #[serde(rename = "model_list")]
    ModelList {
        /// Available models grouped by provider.
        models: Vec<WebModelEntry>,
    },

    /// Client requests a model change.
    #[serde(rename = "model_change")]
    ModelChange {
        /// Target provider name.
        provider: String,
        /// Target model id.
        model: String,
    },

    /// Server confirms model change.
    #[serde(rename = "model_changed")]
    ModelChanged {
        /// New active provider.
        provider: String,
        /// New active model.
        model: String,
    },

    /// Client requests provider auth status list.
    #[serde(rename = "provider_auth_request")]
    ProviderAuthRequest,

    /// Server sends provider auth status list.
    #[serde(rename = "provider_auth_status")]
    ProviderAuthStatus {
        /// Available providers with auth status.
        providers: Vec<WebProviderAuthEntry>,
    },

    /// Client requests provider login (OAuth, API key, or code completion).
    #[serde(rename = "provider_login")]
    ProviderLogin {
        /// Target provider name.
        provider: String,
        /// Optional API key for direct-key providers.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        api_key: Option<String>,
        /// Optional endpoint URL for endpoint+key providers.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        endpoint: Option<String>,
        /// Optional authorization code for code-display OAuth flows.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        auth_code: Option<String>,
    },

    /// Server sends OAuth auth URL for the client to open.
    #[serde(rename = "provider_auth_url")]
    ProviderAuthUrl {
        /// Provider name this URL belongs to.
        provider: String,
        /// Full authorization URL to open in a browser window.
        auth_url: String,
        /// Flow type: "redirect" for localhost callback, "code_display" for code input.
        flow_type: String,
    },

    /// Server confirms provider auth completed.
    #[serde(rename = "provider_auth_completed")]
    ProviderAuthCompleted {
        /// Provider name that completed authentication.
        provider: String,
        /// Whether authentication succeeded.
        success: bool,
        /// Human-readable result message.
        message: String,
    },

    /// Client requests cancellation of current agent processing.
    #[serde(rename = "cancel_generation")]
    CancelGeneration,

    /// Server confirms generation was cancelled.
    #[serde(rename = "generation_cancelled")]
    GenerationCancelled,

    /// Server requests tool call approval from the client.
    #[serde(rename = "tool_approval_request")]
    ToolApprovalRequest {
        /// Tool-call identifier from the LLM.
        call_id: String,
        /// Name of the tool to be executed.
        tool_name: String,
        /// JSON arguments for the tool call.
        arguments: serde_json::Value,
    },

    /// Client sends tool call approval decision.
    #[serde(rename = "tool_approval_response")]
    ToolApprovalResponse {
        /// Tool-call identifier this decision applies to.
        call_id: String,
        /// Decision: "approve", "reject", or "allow_for_session".
        decision: String,
    },
}

/// Callback type for model change requests from web clients.
pub type ModelChangeCallback = Arc<dyn Fn(String, String) + Send + Sync>;

/// Callback returning provider auth status list.
pub type ProviderListCallback = Arc<dyn Fn() -> Vec<WebProviderAuthEntry> + Send + Sync>;

/// Async callback for handling provider authentication requests.
///
/// Receives a [`ProviderAuthIntent`] describing the login attempt and returns
/// either an OAuth URL to open or a completion message.
pub type ProviderAuthCallback = Arc<
    dyn Fn(
            ProviderAuthIntent,
        ) -> std::pin::Pin<
            Box<dyn std::future::Future<Output = Result<ProviderAuthResult, String>> + Send>,
        > + Send
        + Sync,
>;

/// Intent sent to the provider auth callback.
#[derive(Debug, Clone)]
pub struct ProviderAuthIntent {
    /// Target provider name (e.g. "openai", "anthropic").
    pub provider: String,
    /// API key supplied by the user (for API-key providers).
    pub api_key: Option<String>,
    /// Endpoint URL (for endpoint+key providers like Azure).
    pub endpoint: Option<String>,
    /// Authorization code from code-display OAuth flow.
    pub auth_code: Option<String>,
}

/// Result from the provider auth callback.
#[derive(Debug, Clone)]
pub enum ProviderAuthResult {
    /// OAuth URL to open in the browser.
    OAuthUrl {
        /// Full authorization URL.
        url: String,
        /// Flow type: "redirect" or "code_display".
        flow_type: String,
    },
    /// Authentication completed successfully.
    Completed {
        /// Human-readable success message.
        message: String,
    },
}

/// Pending tool approval requests awaiting user decisions.
///
/// Maps `call_id` to a oneshot sender that delivers the user's decision
/// back to the agent runtime.
pub(super) type PendingApprovals =
    Arc<DashMap<String, tokio::sync::oneshot::Sender<proto::ToolApprovalDecision>>>;

/// Tool approval handler for web clients.
///
/// Sends approval requests over WebSocket and waits for the user's decision.
/// Pending requests are tracked in a shared `DashMap` keyed by `call_id`.
pub struct WebApprovalHandler {
    ws_broadcast: broadcast::Sender<WsMessage>,
    pending: PendingApprovals,
}

impl WebApprovalHandler {
    /// Creates a new web approval handler.
    pub fn new(ws_broadcast: broadcast::Sender<WsMessage>, pending: PendingApprovals) -> Self {
        Self {
            ws_broadcast,
            pending,
        }
    }
}

struct PendingApprovalGuard {
    pending: PendingApprovals,
    call_id: String,
    defused: bool,
}

impl PendingApprovalGuard {
    fn new(pending: PendingApprovals, call_id: String) -> Self {
        Self {
            pending,
            call_id,
            defused: false,
        }
    }

    fn defuse(&mut self) {
        self.defused = true;
    }
}

impl Drop for PendingApprovalGuard {
    fn drop(&mut self) {
        if !self.defused {
            self.pending.remove(&self.call_id);
        }
    }
}

#[async_trait]
impl proto::ToolApprovalHandler for WebApprovalHandler {
    async fn request_approval(
        &self,
        req: proto::ToolApprovalRequest,
    ) -> proto::ToolApprovalDecision {
        let (tx, rx) = tokio::sync::oneshot::channel();
        self.pending.insert(req.call_id.clone(), tx);

        let mut guard = PendingApprovalGuard::new(self.pending.clone(), req.call_id.clone());

        let ws_msg = WsMessage::ToolApprovalRequest {
            call_id: req.call_id.clone(),
            tool_name: req.tool_name,
            arguments: req.arguments,
        };

        let _ = self.ws_broadcast.send(ws_msg);

        match rx.await {
            Ok(decision) => {
                guard.defuse();
                decision
            }
            Err(_) => proto::ToolApprovalDecision::Reject,
        }
    }
}

/// Provider auth entry sent to web clients.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WebProviderAuthEntry {
    pub name: String,
    pub display_name: String,
    pub auth_mode: String,
    pub authenticated: bool,
    pub supports_runtime: bool,
}

/// A model entry sent to web clients.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct WebModelEntry {
    pub provider: String,
    pub model: String,
    pub recommended: bool,
}

/// A single message in the conversation history sent to a web client.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct WebHistoryMessage {
    pub role: String,
    pub content: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tool_name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tool_call_id: Option<String>,
    pub created_at: String,
}

/// Provides session conversation history for the web adapter.
#[async_trait]
pub trait SessionLoader: Send + Sync {
    /// Load all messages for the given session id, ordered oldest-first.
    async fn load_session_messages(&self, session_id: &str) -> Result<Vec<AgentMessage>, String>;
}

/// Convert a list of `AgentMessage` to `WebHistoryMessage`, skipping system messages.
pub(super) fn to_web_history(messages: Vec<AgentMessage>) -> Vec<WebHistoryMessage> {
    messages
        .into_iter()
        .filter(|m| m.role != Role::System)
        .map(|m| WebHistoryMessage {
            role: m.role.to_string(),
            content: m.content,
            tool_name: m.tool_name,
            tool_call_id: m.tool_call_id,
            created_at: m.created_at.to_rfc3339(),
        })
        .collect()
}

/// Session entry payload shown in the web session sidebar.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct WebSessionEntry {
    pub id: String,
    pub channel_id: String,
    pub updated_at: String,
    pub preview: String,
}

/// Query parameters for WebSocket upgrade request.
#[derive(Debug, Deserialize)]
pub struct WsConnectParams {
    pub token: Option<String>,
    pub session_token: Option<String>,
    pub client_id: Option<String>,
    pub session_id: Option<String>,
}

/// A server-side auth session created by `POST /auth`.
#[derive(Debug, Clone)]
pub(super) struct AuthSession {
    pub(super) expires_at: DateTime<Utc>,
    pub(super) client_id: String,
}

pub(super) const SESSION_TOKEN_TTL_HOURS: i64 = 24;

#[derive(Debug, Deserialize)]
pub(super) struct AuthRequest {
    pub(super) token: String,
    #[serde(default)]
    pub(super) client_id: Option<String>,
}

#[derive(Debug, Serialize)]
pub(super) struct AuthResponse {
    pub(super) success: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub(super) session_token: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub(super) client_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub(super) expires_at: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub(super) error: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub(super) provider: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub(super) model: Option<String>,
}

pub(super) fn generate_session_token() -> String {
    use std::fmt::Write as _;
    let mut bytes = [0u8; 32];
    rand::rngs::OsRng.fill_bytes(&mut bytes);
    let mut s = String::with_capacity(64);
    for b in &bytes {
        write!(s, "{b:02x}").unwrap();
    }
    s
}

pub(super) struct WebState {
    pub(super) auth_token: String,
    pub(super) event_tx: mpsc::Sender<ChannelEvent>,
    pub(super) auth_sessions: Arc<DashMap<String, AuthSession>>,
    pub(super) clients: Arc<DashMap<String, mpsc::Sender<AgentResponse>>>,
    pub(super) selected_provider: Arc<RwLock<Option<String>>>,
    pub(super) selected_model: Arc<RwLock<Option<String>>>,
    pub(super) shared_session_id: String,
    pub(super) sessions: Arc<RwLock<Arc<Vec<WebSessionEntry>>>>,
    pub(super) session_loader: Option<Arc<dyn SessionLoader>>,
    #[allow(dead_code)]
    pub(super) static_dir: String,
    pub(super) index_html: Option<String>,
    pub(super) model_change_cb: Option<ModelChangeCallback>,
    pub(super) model_list: Arc<Vec<WebModelEntry>>,
    pub(super) provider_list_cb: Option<ProviderListCallback>,
    pub(super) provider_auth_cb: Option<ProviderAuthCallback>,
    pub(super) pending_approvals: PendingApprovals,
    pub(super) approval_broadcast: broadcast::Sender<WsMessage>,
}
